---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-gitops-infra
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/rvvg/awesome-flux-infra.git
  ignore: |
    # exclude README.md
    /README.md
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd-gitops-infra
  namespace: flux-system
spec:
  dependsOn:
    - name: fluxcd-gitops-crds
  interval: 10m
  path: ./clusters/spot-rackspace-demo-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-gitops-infra
  postBuild:
    substitute:
      env: "spot-rackspace-demo-1"
      cluster_name: "spot-rackspace-demo-1"
      cluster_subdomain: "example.com"
